// Where `no-hardcoded-ui-text` runs, read by the root `oxlint.config.ts` and by the rule's test.
// Paths are relative to the repo root, as the config's globs are.

const front = (path: string) => `apps/frontend/src/${path}`;

// The delivered front: JSX lives in `.tsx` files only.
export const uiTextFiles = [front("**/*.tsx")];

// Never delivered, so never translated: the tests, and the code only a dev build has (the
// `/dev/*` pages, the Face-off lab, the Aura gallery, the dev email sign-in).
export const outOfScopeFiles = [
  "**/*.test.tsx",
  "test/**",
  "pages/aura-gallery-page.tsx",
  "pages/aura-maniac-prototype-page.tsx",
  "pages/duel-hud-dev-page.tsx",
  "pages/face-off-dev-page.tsx",
  "pages/tier-up-dev-page.tsx",
  "components/aura-gallery/**",
  "components/aura-maniac-prototype/**",
  "components/duel-hud-dev/**",
  "components/face-off-lab/**",
  "components/tier-up-dev/**",
  "components/auth/dev-email-sign-in.tsx",
].map(front);

// The files that still have hardcoded text. Each extraction ticket removes the ones it
// translates, and the list is empty once English opens. The test fails on a file that no
// longer has any, so it cannot stay here.
export const untranslatedFiles = [
  "components/activity/activity-column.tsx",
  "components/activity/activity-empty.tsx",
  "components/activity/arrival-activity-item.tsx",
  "components/activity/duel-activity-item.tsx",
  "components/activity/friendship-activity-item.tsx",
  "components/challenge/challenge-button.tsx",
  "components/challenge/challenge-time-left.tsx",
  "components/challenge/received-challenge-card.tsx",
  "components/challenge/sent-challenge-card.tsx",
  "components/challenge/waiting-challenges.tsx",
  "components/desktop-only.tsx",
  "components/duel-chart/duel-chart-legend.tsx",
  "components/duel-chart/duel-chart.tsx",
  "components/duel-history/duel-details-error.tsx",
  "components/duel-history/duel-details-header.tsx",
  "components/duel-history/duel-history-empty.tsx",
  "components/duel-history/duel-history-item.tsx",
  "components/duel-history/duel-history-list.tsx",
  "components/duel-history/duel-history-opponent.tsx",
  "components/duel-history/duel-replay-button.tsx",
  "components/duel-history/duel-results-table.tsx",
  "components/duel-history/duels-header.tsx",
  "components/duel-history/finished-duel-outcome.tsx",
  "components/duel-hud/duel-band-half.tsx",
  "components/duel-hud/duel-callouts.tsx",
  "components/duel-hud/duel-combo-gauge.tsx",
  "components/duel-hud/duel-disc.tsx",
  "components/duel-hud/duel-multiplier.tsx",
  "components/duel-scene/duel-format-chip.tsx",
  "components/duel/duel-connection.tsx",
  "components/duel/duel-ended.tsx",
  "components/duel/duel-rank.tsx",
  "components/duel/leave-duel.tsx",
  "components/duel/placement-progress.tsx",
  "components/duel/queue-locked.tsx",
  "components/duel/queue-search.tsx",
  "components/duel/queue-tip.tsx",
  "components/duel/queue-wait.tsx",
  "components/duel/rank-revealed.tsx",
  "components/duel/replay-duel-link.tsx",
  "components/face-off/face-off-count.tsx",
  "components/face-off/face-off-form.tsx",
  "components/face-off/face-off-mute.tsx",
  "components/face-off/face-off-rank.tsx",
  "components/face-off/face-off-stake.tsx",
  "components/friends/friend-list.tsx",
  "components/friends/friend-requests-received.tsx",
  "components/friends/friend-requests-sent.tsx",
  "components/friends/friend-row.tsx",
  "components/friends/friends-empty.tsx",
  "components/friends/friends-handle-required.tsx",
  "components/friends/friends-header.tsx",
  "components/friends/relation-actions.tsx",
  "components/friends/user-search-results.tsx",
  "components/friends/user-search.tsx",
  "components/leaderboard/leaderboard-empty.tsx",
  "components/leaderboard/leaderboard-header.tsx",
  "components/leaderboard/leaderboard-list.tsx",
  "components/leaderboard/leaderboard-place-pending.tsx",
  "components/leaderboard/leaderboard-place-ranked.tsx",
  "components/leaderboard/leaderboard-place.tsx",
  "components/leaderboard/leaderboard-podium.tsx",
  "components/leaderboard/leaderboard-you.tsx",
  "components/leaderboard/tier-legend-row.tsx",
  "components/leaderboard/tier-legend.tsx",
  "components/match-proposal/match-proposal-actions.tsx",
  "components/match-proposal/match-proposal-header.tsx",
  "components/match-proposal/match-proposal-player.tsx",
  "components/ornament/ornament-picker.tsx",
  "components/profile/own-profile-empty.tsx",
  "components/profile/profile-hero-rank-text.tsx",
  "components/profile/profile-hero.tsx",
  "components/profile/profile-progression.tsx",
  "components/profile/profile-public-link.tsx",
  "components/profile/profile-stats.tsx",
  "components/profile/progression-chart.tsx",
  "components/profile/progression-charts.tsx",
  "components/profile/sign-in-prompt.tsx",
  "components/profile/stats-tiles.tsx",
  "components/profile/user-profile-empty.tsx",
  "components/ranked/play-ranked-link.tsx",
  "components/ranked/ranked-aside.tsx",
  "components/ranked/ranked-place-body.tsx",
  "components/ranked/ranked-place.tsx",
  "components/ranked/ranked-tier-row.tsx",
  "components/ranked/ranked-tiers.tsx",
  "components/replay/replay-controls.tsx",
  "components/replay/replay-duel-format.tsx",
  "components/replay/replay-forfeit-marker.tsx",
  "components/replay/replay-header.tsx",
  "components/replay/replay-lecture.tsx",
  "components/replay/replay-score-card.tsx",
  "components/replay/replay-side-picker.tsx",
  "components/replay/replay-speed-picker.tsx",
  "components/replay/replay-timeline.tsx",
  "components/run/focus-overlay.tsx",
  "components/run/keystroke-input.tsx",
  "components/run/next-run-button.tsx",
  "components/run/next-run-keys.tsx",
  "components/run/replay-button.tsx",
  "components/run/score-stats.tsx",
  "components/run/time-left.tsx",
  "components/settings/duel-format.tsx",
  "components/settings/settings-bar.tsx",
  "components/sound/sound-icon.tsx",
  "components/sound/sound-pack-picker.tsx",
  "components/sound/volume-slider.tsx",
  "components/theme/active-theme.tsx",
  "components/theme/theme-effects.tsx",
  "components/theme/theme-option.tsx",
  "components/theme/theme-picker.tsx",
  "components/theme/theme-preview.tsx",
  "components/theme/theme-roles.tsx",
  "components/tier-up/caption/tier-up-caption.tsx",
  "components/tier/rank/tp-progress.tsx",
  "pages/health-page.tsx",
  "pages/home-page.tsx",
  "pages/replay-error-page.tsx",
  "pages/replay-page.tsx",
  "pages/themes-page.tsx",
  "pages/user-profile-not-found-page.tsx",
  "pages/user-profile-page.tsx",
].map(front);
