// Step 2: from data/counts.tsv, minus data/excluded.txt, the 1,000 most frequent words split into
// weights, written to the typing engine's English Word list version 2.
import { readFileSync, writeFileSync } from "node:fs";

import { countsFile, excludedFile, outputFile } from "./paths";

// The most frequent first: 100 words of weight 4, 300 of weight 2, 600 of weight 1.
const groups = [
  { weight: 4, size: 100 },
  { weight: 2, size: 300 },
  { weight: 1, size: 600 },
];

const notice = `/*! typomaniac English Word list version 2, built from SCOWL and Google Books Ngram.
 *
 * SCOWL (Spell Checker Oriented Word Lists), http://wordlist.aspell.net
 * Copyright 2000-2018 by Kevin Atkinson
 *
 * Permission to use, copy, modify, distribute and sell these word lists, the associated scripts,
 * the output created from the scripts, and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appears in all copies and that both that
 * copyright notice and this permission notice appear in supporting documentation. Kevin Atkinson
 * makes no representations about the suitability of this array for any purpose. It is provided
 * "as is" without express or implied warranty.
 *
 * Word frequencies: Google Books Ngram Viewer, http://books.google.com/ngrams, licensed under
 * CC BY 3.0, https://creativecommons.org/licenses/by/3.0/
 */`;

const header = `// Generated by tools/word-list (\`bun run generate\`), not taken from Monkeytype (GPL-3): the 1,000
// most frequent SCOWL words in Google Books since 2000, lowercase \`[a-z]\`, 2 to 10 letters.
// Word list version 2 of English: released, so never edited. A change is a new version, otherwise
// the recorded Keystrokes would no longer replay on their Text.`;

// `word<TAB>matches`, already sorted from the most frequent.
const counted = readFileSync(countsFile, "utf8")
  .split("\n")
  .flatMap((line) => line.split("\t")[0] || []);

// One word per line, then `# why`; a line starting with `#` is a comment.
const excluded = new Set(
  readFileSync(excludedFile, "utf8")
    .split("\n")
    .flatMap((line) => line.split("#")[0]?.trim() || []),
);

const kept = counted.filter((word) => !excluded.has(word));

let start = 0;

const weighted = groups.map(({ weight, size }) => {
  const words = kept.slice(start, start + size).toSorted();

  start += size;

  return { weight, words };
});

if (start > kept.length) {
  throw new Error(`Only ${kept.length} words left, ${start} needed`);
}

const groupSource = ({ weight, words }: { weight: number; words: string[] }) =>
  `  {\n    weight: ${weight},\n    words: [\n${words.map((word) => `      "${word}",\n`).join("")}    ],\n  },\n`;

writeFileSync(
  outputFile,
  // The notice sits on the list itself, not on the type import the bundler erases with it.
  `import type { WeightGroup } from "../text";\n\n${notice}\n${header}\nexport const enV2: readonly WeightGroup[] = [\n${weighted.map(groupSource).join("")}];\n`,
);

// Formatted like the rest of the repo, so a rebuild of the same data changes nothing.
const format = Bun.spawnSync(["bunx", "oxfmt", outputFile]);

if (format.exitCode !== 0) {
  throw new Error(`oxfmt failed: ${format.stderr.toString()}`);
}

const averageLength = (words: string[]) =>
  (words.reduce((sum, word) => sum + word.length, 0) / words.length).toFixed(2);

console.log(`${counted.length} counted, ${excluded.size} excluded, last kept: ${kept[start - 1]}`);

for (const { weight, words } of weighted) {
  console.log(
    `weight ${weight}: ${words.length} words, ${averageLength(words)} letters on average`,
  );
}
