/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankedRouteImport } from './routes/ranked'
import { Route as RunRouteImport } from './routes/run'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as HistoryDuelIdRouteImport } from './routes/history_.$duelId'
import { Route as UHandleRouteImport } from './routes/u.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedRoute = RankedRouteImport.update({
  id: '/ranked',
  path: '/ranked',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryDuelIdRoute = HistoryDuelIdRouteImport.update({
  id: '/history_/$duelId',
  path: '/history/$duelId',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duel': typeof DuelRoute
  '/friends': typeof FriendsRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/run': typeof RunRoute
  '/themes': typeof ThemesRoute
  '/history/$duelId': typeof HistoryDuelIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duel': typeof DuelRoute
  '/friends': typeof FriendsRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/run': typeof RunRoute
  '/themes': typeof ThemesRoute
  '/history/$duelId': typeof HistoryDuelIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duel': typeof DuelRoute
  '/friends': typeof FriendsRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/run': typeof RunRoute
  '/themes': typeof ThemesRoute
  '/history_/$duelId': typeof HistoryDuelIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duel'
    | '/friends'
    | '/health'
    | '/history'
    | '/leaderboard'
    | '/profile'
    | '/ranked'
    | '/run'
    | '/themes'
    | '/history/$duelId'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/duel'
    | '/friends'
    | '/health'
    | '/history'
    | '/leaderboard'
    | '/profile'
    | '/ranked'
    | '/run'
    | '/themes'
    | '/history/$duelId'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/duel'
    | '/friends'
    | '/health'
    | '/history'
    | '/leaderboard'
    | '/profile'
    | '/ranked'
    | '/run'
    | '/themes'
    | '/history_/$duelId'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuelRoute: typeof DuelRoute
  FriendsRoute: typeof FriendsRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  RankedRoute: typeof RankedRoute
  RunRoute: typeof RunRoute
  ThemesRoute: typeof ThemesRoute
  HistoryDuelIdRoute: typeof HistoryDuelIdRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked': {
      id: '/ranked'
      path: '/ranked'
      fullPath: '/ranked'
      preLoaderRoute: typeof RankedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$duelId': {
      id: '/history_/$duelId'
      path: '/history/$duelId'
      fullPath: '/history/$duelId'
      preLoaderRoute: typeof HistoryDuelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuelRoute: DuelRoute,
  FriendsRoute: FriendsRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  RankedRoute: RankedRoute,
  RunRoute: RunRoute,
  ThemesRoute: ThemesRoute,
  HistoryDuelIdRoute: HistoryDuelIdRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
